name: Indexing build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 2 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup node env
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: cache managing
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: install dependencies
        run: npm install
      - name: generate indexing files
        run: npm run start
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      - name: push new indexing files
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
